#template for the menu, everyone can add the code for their questions to each function
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv("vgsales.csv")

# placeholder functions for each team members question
def calculate_sales_by_genre(data):
    print('\n ----- Total global sales by genre -----')

    unique_genres = data["Genre"].unique()  # reads genre column and extracts unique genres

    print('\nList of genres: ')
    print(f"{unique_genres}")  # lists and prints unique genres

    checker = True  # boolean checker set to true to conduct a verification for user input
    while checker:  # while loop used (if checker is true) to repeatedly check and execute code
        chosenGenre = input('\nPlease enter a genre from the list above: ')  # takes in user input

        if chosenGenre in unique_genres:
            genre_data = data[data["Genre"] == chosenGenre]  # checks user input against matching words in the genre column

            total_sales = genre_data['Global_Sales'].sum()  # extracts global sales column and sums all sales generated by matching chosen genre
            print(f"The total global sales for {chosenGenre} is {total_sales}")
            checker = False  # Sets checker to false, exiting the loop
        else:
            print("\nInvalid input.")  # this line is executed if user input doesn't match

def popular_genre_by_year(data):
    print('\n ----- Most popular genre by year -----')

    unique_years = data['Year'].dropna().unique()  # extracts unique years, not including games that have 'NA'
    year = unique_years.astype(int)  # converts year data into int so we can form comparisons
    year.sort()  # sort function to sort year data in order from lowest to highest

    print('\nList of years: ')
    print(f"{year}")

    chosenYear = input('\nPlease select a year from the list above to view the most popular genre that year: ')
    chosenYear = int(chosenYear)  # converts input from string to int so that year data and input data can be compared

    if chosenYear in year:
        year_data = data[data['Year'] == chosenYear]  # filters and finds user input match with 'Year'

        global_sales = year_data['Global_Sales']  # filters through global sales column and only extracts and stores
        max_globalsales = max(global_sales)  # calculates and stores max value in global sales
        pop_genre = year_data.loc[year_data['Global_Sales'] == max_globalsales, 'Genre']  # finds the genre that matches the max global sale found (same row diff column)

        print(f"The most popular genre for that year is: {pop_genre}")

    else:
        print('\nInvalid input.')

        print(f"\n{year}")

        chosenYear = input('\nPlease select a year from the list above to view the most popular genre that year: ')
        chosenYear = int(chosenYear)

        if chosenYear in year:
            year_data = data[data["Year"] == chosenYear]

            global_sales = year_data['Global_Sales']
            max_globalsales = max(global_sales)
            pop_genre = year_data.loc[year_data['Global_Sales'] == max_globalsales, 'Genre']

        print(f"The most popular genre for that year is: {pop_genre}")

def main_menu():
    while True:
        print("\n      ----- Main Menu -----    ")
        print("- Enter number 1 to calculate total sales by genre.")
        print("- Enter number 2 to view the most popular genre for a specific year.")
        print("- Enter number 3 to exit system.")
        
        choice = input("Enter your choice (1-3): ")

        match choice:
            case "1":
                calculate_sales_by_genre(data)
            case "2":
                popular_genre_by_year(data)
            case "3":
                print("System exited")
                break
            case _:
                print("Invalid choice")


if __name__ == "__main__":
    main_menu()                 