import pandas as pd #import pandas for data extraction

data = pd.read_csv('vgsales.csv') #reads and loads video game sales file content

print('\n ----- Total global sales by genre -----')


unique_genres = data["Genre"].unique() #reads genre column and extracgts unique genres

print('\nList of genres: ')
print(f"{unique_genres}") #lists and prints unique genres

chosenGenre = input('\nPlease enter a genre from the list above: ') #takes in user input


if chosenGenre in unique_genres:
    genre_data = data[data["Genre"] == chosenGenre] #checks user input against matching words in the genre column

    total_sales = genre_data['Global_Sales'].sum() #extracts global sales column and sums all sales generated by matching chosen genre
    print(f"The total global sales for {chosenGenre} is {total_sales}") 


else:
    print('\nInvalid input.') # else if user input doesnt match execute following code below
    print(f"\n{unique_genres}") #lists unique genres again

    chosenGenre = input('\nPlease enter a genre from the list above: ') #takes in correct user input again
    
    if chosenGenre in unique_genres: #if statement conducted here
     genre_data = data[data["Genre"] == chosenGenre]
 
    total_sales = genre_data['Global_Sales'].sum()
    print(f"The total global sales for {chosenGenre} is {total_sales}")